from datetime import datetime, timedelta

from fastapi import FastAPI
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker
from sqlalchemy.pool import StaticPool

import app.models  # noqa: F401
from app.api import automation_alerts, case_intelligence, reports
from app.database import Base, get_db
from app.models.case import Case
from app.models.conclusion import Conclusion
from app.models.ai_model import AIModel
from app.models.meeting import Meeting
from app.models.report import Report
from app.services.automation_alert_service import AutomationAlertService
from test_case_result_access import result_data  # noqa: F401
from test_case_results import db_session  # noqa: F401
from test_conclusion_result_reuse import current_profile, frozen_result  # noqa: F401


def _session() -> Session:
    engine = create_engine(
        "sqlite://",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(bind=engine)
    session_local = sessionmaker(autocommit=False, autoflush=False, bind=engine)
    return session_local()


def _client(db_session: Session) -> TestClient:
    app = FastAPI()
    app.include_router(case_intelligence.router, prefix="/api/case-intelligence")
    app.include_router(automation_alerts.router, prefix="/api/automation-alerts")
    app.include_router(reports.router, prefix="/api/reports")

    def override_get_db():
        yield db_session

    app.dependency_overrides[get_db] = override_get_db
    return TestClient(app)


def _add_case(db: Session, number: str, days_ago: int, hour: int, description: str) -> Case:
    occurred = (datetime.utcnow() - timedelta(days=days_ago)).replace(
        hour=hour,
        minute=20,
        second=0,
        microsecond=0,
    )
    case = Case(
        case_number=number,
        occurred_time=occurred,
        location="南区12号井附近",
        latitude=39.9,
        longitude=116.4,
        case_type="涉油盗窃",
        description=description,
        facility_type="井口",
        oil_type="原油",
        source_type="巡逻发现",
        status="closed",
    )
    db.add(case)
    db.commit()
    db.refresh(case)
    return case


def test_case_report_exposes_normalized_ai_output_with_review_boundary():
    db = _session()
    client = _client(db)
    selected = _add_case(
        db,
        "AI-B-001",
        1,
        2,
        "凌晨发现皮卡车靠近井场，车内有油桶和软管，现场照明不足。",
    )
    _add_case(
        db,
        "AI-B-002",
        8,
        3,
        "夜间厢货车停在井场便道旁，发现油桶和抽油泵，周边监控盲区。",
    )

    response = client.get("/api/case-intelligence/report", params={"case_id": selected.id, "days": 30})

    assert response.status_code == 404
    # The retired live-report GET must not recompute facts. Structured result
    # bodies and their boundaries are exercised by the material tests below.


def test_alert_triage_pack_uses_same_ai_output_contract_without_dispatch_language():
    db = _session()
    client = _client(db)
    # Historical synthetic records are fixtures, never generated by a business API.
    alert = AutomationAlertService.seed_simulated_alerts(db)[0]

    response = client.get(f"/api/automation-alerts/{alert.id}/triage-pack")

    assert response.status_code == 200
    ai_output = response.json()["ai_output"]
    assert ai_output["output_type"] == "automation_alert_triage_pack"
    assert ai_output["draft_status"] == "draft"
    assert ai_output["review_status"] == "pending_review"
    assert ai_output["model_status"] == "deterministic_fallback"
    assert ai_output["facts"]
    assert ai_output["inferences"]
    assert ai_output["recommendations"]
    assert ai_output["information_gaps"]
    assert any(ref["id"].startswith("alert:") for ref in ai_output["evidence_refs"])
    assert "## 建议与补齐事项" in ai_output["markdown"]
    assert "派发巡逻" not in ai_output["markdown"]
    assert "不得把告警建议写成已执行任务" in "；".join(ai_output["boundary"])


def test_report_api_exposes_normalized_review_draft_markdown():
    db = _session()
    client = _client(db)
    db.add_all(
        [
            AIModel(
                id=model_id,
                name=f"report-model-{model_id}",
                provider="local",
                model_name="fixture",
                api_key="test-only",
                role="moderator" if model_id == 1 else "analyst",
            )
            for model_id in (1, 2, 3)
        ]
    )
    db.flush()
    meeting = Meeting(
        meeting_id="MEET-B-001",
        case_ids=[],
        status="completed",
        moderator_model_id=1,
        analyst_model_ids=[2, 3],
    )
    db.add(meeting)
    db.flush()
    report = Report(
        meeting_id=meeting.meeting_id,
        report_type="comprehensive",
        content={
            "summary": "会议认为应复核夜间井场同类条件。",
            "conclusions": "同类案件存在时空条件相似性。",
            "recommendations": ["补齐现场照片", "人工复核相似条件"],
        },
        consensus_points=["夜间井场要重点复核"],
        disagreement_points=[],
        model_contributions={"analyst_a": "提炼事实依据"},
    )
    db.add(report)
    db.commit()
    db.refresh(report)

    response = client.get(f"/api/reports/{report.id}")

    assert response.status_code == 200
    payload = response.json()
    assert payload["draft_status"] == "draft"
    assert payload["review_status"] == "pending_review"
    assert payload["ai_output"]["output_type"] == "meeting_report_draft"
    assert payload["ai_output"]["facts"]
    assert payload["ai_output"]["inferences"]
    assert payload["ai_output"]["recommendations"]
    assert payload["ai_output"]["evidence_refs"][0]["id"] == f"report:{report.id}"
    assert "## 事实依据" in payload["ai_output"]["markdown"]
    assert "## 证据索引" in payload["ai_output"]["markdown"]


# v6.5 preserves old contents as historical materials, never upgrades an old
# candidate into "facts" by running a fallback formatter.
from test_result_materials_v65 import material_db, query_db, search_db, client, saved_case  # noqa: F401


def test_material_body_retains_frozen_boundaries_without_draft_factory(material_db):
    _, result = saved_case(material_db)
    with client(material_db) as http:
        view = http.get(f"/api/results/case/{result['id']}").json()
    assert view['body']['content'] == result['content']
    assert view['boundary'] and view['judgments'] == []
    assert material_db.query(Conclusion).count() == 0


def test_legacy_conclusion_reader_does_not_promote_old_text_to_facts(material_db):
    case, _ = saved_case(material_db)
    row = Conclusion(case_id=case.id, summary='旧推断原文', evidence={'key_evidence': ['未核查线索']})
    material_db.add(row)
    material_db.commit()
    with client(material_db) as http:
        response = http.get(f"/api/results/conclusion/{row.id}")
    assert response.status_code == 200
    body = response.json()['body']
    assert body['summary'] == '旧推断原文'
    assert body['evidence'] == {'key_evidence': ['未核查线索']}
    assert 'ai_output' not in body and 'facts' not in body
